### ISSUE TITLE
请求错误: timeout of 5000ms exceeded

### ISSUE THREAD

**Issue by genius94yz** [dotbalo/krm#1]
admin / admin默认账号密码登录提示：
请求错误: timeout of 5000ms exceeded
<img width="268" alt="image" src="https://github.com/dotbalo/krm/assets/35911384/3e4c5eb5-f858-4cf7-a5d4-a00d9043a808">

**Comment by dotbalo** [comment]
您好，请问是在demo环境测试的，还是自行安装的？

**Comment by genius94yz** [comment]
> 您好，请问是在demo环境测试的，还是自行安装的？

你好，是参考部署文档：https://github.com/dotbalo/krm/blob/main/deploy.md
在自己搭建的k8s环境中部署的。

**Comment by dotbalo** [comment]
> > 您好，请问是在demo环境测试的，还是自行安装的？
> 
> 你好，是参考部署文档：https://github.com/dotbalo/krm/blob/main/deploy.md 在自己搭建的k8s环境中部署的。

你把你的部署文件发一下，另外部署的资源名字最好不要更改

**Comment by genius94yz** [comment]
> > > 您好，请问是在demo环境测试的，还是自行安装的？
> > 
> > 
> > 你好，是参考部署文档：https://github.com/dotbalo/krm/blob/main/deploy.md 在自己搭建的k8s环境中部署的。
> 
> 你把你的部署文件发一下，另外部署的资源名字最好不要更改

部署文件和https://github.com/dotbalo/krm/blob/main/deploy.md 写的完全一样，资源名字没有任何改动。

**Comment by dotbalo** [comment]
参考快速部署：
# 需要自行安装git工具，比如 yum install git或者apt-get install git
git clone https://gitee.com/dukuan/k8s-ha-install.git
cd k8s-ha-install
kubectl  create -f krm.yaml
